### ISSUE TITLE
Dont show modal on iOS

### ISSUE THREAD

**Issue by luisfuertes** [alinz/react-native-share-extension#18] opened 2016-11-30 10:41 UTC
Hi, thanks for this component.

On iOS i think all its fine configured but when i press on share to MyAppShareEx, nothing happen. It dont show any popup. 

Some idea? If need some code of my config ask me and i will post it.

Thanks!

**Comment by bengoism** [comment] 2016-12-01 08:28
I have the exact same problem, would be great If we could figure out why :).. Im using React native v.0.37

**Comment by luisfuertes** [comment] 2016-12-01 08:44
My versions:
``` 
    "react": "15.3.2",
    "react-native": "0.33.0",
    "react-native-share-extension": "^1.0.3",
```

**Comment by TheSisb** [comment] 2016-12-06 02:17
Please share your code if you want help.  The issue is relatively broad to guess from.

**Comment by luisfuertes** [comment] 2016-12-07 11:02
@TheSisb ofcourse,

iOS Extension: MyCustomShareEx.m

``` 
#import <Foundation/Foundation.h>
#import "ReactNativeShareExtension.h"
#import "RCTBundleURLProvider.h"
#import "RCTRootView.h"

@interface MyCustomShareEx : ReactNativeShareExtension
@end

@implementation MyCustomShareEx

RCT_EXPORT_MODULE();

- (UIView*) shareView {
  NSURL *jsCodeLocation;
  
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"MyCustomShareEx"
                                               initialProperties:nil
                                                   launchOptions:nil];
  rootView.backgroundColor = nil;
  return rootView;
}

@end
``` 

My index.ios.js:
``` 
import React from 'react'
import { AppRegistry } from 'react-native'
import Index from './src/Index'
import Share from './share.ios'

AppRegistry.registerComponent('MyProject', () => Index);
AppRegistry.registerComponent('MyCustomShareEx', () => Share);
``` 

My share.ios.js:
``` 
import React, { Component } from 'react'
import Modal from 'react-native-modalbox'
import ShareExtension from 'react-native-share-extension'

import {
  Text,
  TextInput,
  View,
  TouchableOpacity
} from 'react-native'

export default class Share extends Component {
  constructor(props, context) {
    super(props, context)
    this.state = {
      isOpen: true,
      type: '',
      value: ''
    }
  }

  async componentDidMount() {
    Alert.alert(null, 'holis')

    try {
      const { type, value } = await ShareExtension.data()
      this.setState({
        type,
        value
      })
    } catch(e) {
      console.log('errrr', e)
      Alert.alert(null, e)
    }
  }

  onClose() {
    ShareExtension.close()
  }

  closing = () => {
    this.setState({
      isOpen: false
    })
  }

  render() {
    return (
      <Modal backdrop={false}
             style={{ backgroundColor: 'transparent' }} position="center" isOpen={this.state.isOpen} onClosed={this.onClose}>
          <View style={{ alignItems: 'center', justifyContent:'center', flex: 1 }}>
            <View style={{ borderColor: 'green', borderWidth: 1, backgroundColor: 'white', height: 200, width: 300 }}>
              <TouchableOpacity onPress={this.closing}>
                <Text>Close</Text>
                <Text>type: { this.state.type }</Text>
                <Text>value: { this.state.value }</Text>
              </TouchableOpacity>
            </View>
          </View>
      </Modal>
    )
  }
}
```

**Comment by parkerdan** [comment] 2016-12-11 14:49
Build your regular project, then build your ShareExtension project.
Restart X-code and React Packager
Try Again.
Check the files in the actual node_modules...See #20.
Check the installation instructions again.
Check the installation instructions again, again...

This is a very important step...
```
since we deleted ShareViewController.m, we need to tell the storyboard of your share extension 
where the view needs to be loaded. So click on MainInterface.storyboard and replace the class field 
from ShareViewController to MyShareEx
```

I just built a new project with minimal resources and things worked.

**Comment by mjracca** [comment] 2016-12-16 13:29
+1

**Comment by luisfuertes** [comment] 2016-12-19 10:56
I try to execute new proyect with basic configuration and share-extension component only.

On new project all works fine.
![captura de pantalla 2016-12-19 a las 11 51 11](https://cloud.githubusercontent.com/assets/18212615/21310203/9ef5158a-c5e1-11e6-9dae-8a1cc56d43ee.png)

But now, i try to do all steps in my project, Now the extension name is the same that the example. MyShareEx.

But on my project it doesnt work. With same share.ios.js than my new project. Here pop up view donesnt appear.
![captura de pantalla 2016-12-19 a las 11 53 59](https://cloud.githubusercontent.com/assets/18212615/21310269/e4b90f54-c5e1-11e6-81a0-1849eeab8c71.png)

**Comment by luisfuertes** [comment] 2016-12-23 10:26
I try to put:
`NSLog(@"MYSHAREEX LOADED");`
on "MyShareEx.m" file, and already checked if it is my `MainInterface.storyboard` view controller.

But on xcode console and on safari console (sharing from safari) dont show any log.

@parkerdan you know how can i continue fixing this?

**Comment by parkerdan** [comment] 2016-12-23 16:26
@luisfuertes, you got a pink box to show...so you did something right.

You tried to make your share extension more complex...and obviously did something wrong.

Share you actual Javascript share extension component/code and I will look at it and try to point out where you went wrong.

Remember this:
    1:  A Share Extension is a separate "app".  This is why you needed to add the static libraries in the build phases.  Are you trying to include other things in your JavaScript component?  IMO, you shouldn't need to include anything other than the basic React components in your Share Extension because of the following statement...
    2:  A Share Extension should be simple.  What is your reason for having it?  IMO, the answer should be so you can send a quick bit of information to your server....nothing more.

**Comment by luisfuertes** [comment] 2016-12-27 09:22
@parkerdan all my config:
![captura de pantalla 2016-12-27 a las 10 12 58](https://cloud.githubusercontent.com/assets/18212615/21496261/7d209b4a-cc1d-11e6-9ccb-f6ce9c1eb679.png)
![captura de pantalla 2016-12-27 a las 10 13 59](https://cloud.githubusercontent.com/assets/18212615/21496262/7d212a74-cc1d-11e6-86a1-c17a41f35fc6.png)
![captura de pantalla 2016-12-27 a las 10 14 22](https://cloud.githubusercontent.com/assets/18212615/21496260/7d205fae-cc1d-11e6-9493-c1f540461e16.png)
![captura de pantalla 2016-12-27 a las 10 15 01](https://cloud.githubusercontent.com/assets/18212615/21496263/7d21436a-cc1d-11e6-9cb0-3f623a4bd620.png)

When i add `rootView.backgroundColor = [UIColor redColor];`  to MyShareEx.m the result:
![captura de pantalla 2016-12-27 a las 10 18 48](https://cloud.githubusercontent.com/assets/18212615/21496309/e18052ba-cc1d-11e6-9feb-564cff55a8f9.png)

But dont load react view.
Simulator log: 
``` 
Dec 27 10:19:44 Mobiles-Mac-mini MyShareEx[3389]: Module AppRegistry is not a registered callable module (calling runApplication)
Dec 27 10:19:44 Mobiles-Mac-mini MyShareEx[3389]: Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)
``` 

My index.ios.js file:
![captura de pantalla 2016-12-27 a las 10 15 01](https://cloud.githubusercontent.com/assets/18212615/21496374/46e8f7ce-cc1e-11e6-9030-9a01a2881b62.png)

And share.ios.js code (is the same that other proyect where it works:
``` 
import React, { Component } from 'react'
import ShareExtension from 'react-native-share-extension'

import {
  Text,
  TextInput,
  View,
  TouchableOpacity
} from 'react-native'

export default class Share extends Component {
  constructor(props, context) {
    super(props, context)
    this.state = {
      isOpen: true,
      type: '',
      value: ''
    }
  }

  async componentDidMount() {
    try {
      const { type, value } = await ShareExtension.data()
      this.setState({
        type,
        value
      })
    } catch(e) {
      console.log('errrr', e)
    }
  }

  onClose() {
    ShareExtension.close()
  }

  closing = () => {
    this.setState({
      isOpen: false
    })
  }

  render() {
    return (
      <View style={{ height:500, width:300, backgroundColor:'deeppink' }} />
    )
  }
}
```

**Comment by vinicius-sabadim** [comment] 2017-01-09 20:27
I'm facing the same error here.
I found that the error is on the other project.

```js
AppRegistry.registerComponent('App', () => App)
AppRegistry.registerComponent('MyShareEx', () => Share)
```

When I comment all the `import` from my `App` component, all starts to work.

**Comment by luisfuertes** [comment] 2017-01-10 14:06
I try: 

MyShareEx.m
``` 
#import <Foundation/Foundation.h>
#import "ReactNativeShareExtension.h"
#import "RCTBundleURLProvider.h"
#import "RCTRootView.h"

@interface MyShareEx : ReactNativeShareExtension
@end

@implementation MyShareEx

RCT_EXPORT_MODULE();

- (UIView*) shareView {
  NSURL *jsCodeLocation;

  
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios-extension" fallbackResource:nil];
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"MyShareEx"
                                               initialProperties:nil
                                                   launchOptions:nil];
  rootView.backgroundColor = nil;

  return rootView;
}

@end
```

And index.ios-extension.js
``` 
import React from 'react'
import { AppRegistry } from 'react-native'
import Share from './share.ios'

AppRegistry.registerComponent('MyShareEx', () => Share)
``` 

And now it works on iOS simulator, but dont work on real iOS device.

**Comment by alinz** [comment] 2017-01-10 14:41
@luisfuertes guys I have no problem using this, and as far as I know the doc is pretty much describe the process. Have you looked into this section of doc? https://github.com/alinz/react-native-share-extension#test-on-device-without-dev-server

**Comment by luisfuertes** [comment] 2017-01-10 14:44
Yes, i have that script implemented on my code. But it doesnt work

**Comment by luisfuertes** [comment] 2017-01-10 16:44
Full log: 
![captura de pantalla 2017-01-10 a las 17 43 38](https://cloud.githubusercontent.com/assets/18212615/21815298/5ef1e68e-d75c-11e6-8425-131f7f8b3c0c.png)

**Comment by luisfuertes** [comment] 2017-01-12 09:05
If i comment all index:
Index.js
```
import { View,	Navigator,	StyleSheet,	TouchableOpacity,	Image,	Dimensions,	BackAndroid,	Platform,	ToastAndroid,	Text,	Alert, } from 'react-native'
import React, { Component } from 'react'

export default class Index extends Component {
	render(){
		return(
			<View style={{flex: 1, backgroundColor: 'blue'}}/>
		)
	}
}
```  
New safari JSContext log: 
`main.jsbundle (línea 824)Application MyShareEx has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.`

**Comment by alinz** [comment] 2017-01-13 15:48
@luisfuertes can you change the workflow. Instead of login in the user in share extension, they should login in your app first and then you can access the the token from share extension. I haven't actually see any apps let's you login in share extension. They usually prompt you to log in inside app or use deep liking to open up your app.

At the moment, I'm doing exactly like that in my app. If users are not logged in, I push them back to main app for login procedure.

**Comment by luisfuertes** [comment] 2017-01-13 16:06
The problem is what i dont use google login on extension. 

You can see my extension code some post before.

The google import is in my main app. But on extension log, say that it need the google (and more imports), dont know why

**Comment by adrianotadao** [comment] 2017-01-18 14:33
@luisfuertes There is something wrong with the google. We had some problem similar here and when something goes wrong, the react-native return a generic error. 

- What we did that had solved our problem: 
We added the lib, in our case was `react-native-cookies` on Link Binary With Libraries.
![9oa_gkw9](https://cloud.githubusercontent.com/assets/387138/22067838/093be4fa-dd7a-11e6-8690-2ad2f85d18ae.png)

- We use a lot the command `react-native log-ios` to see what is happening because a small error can return the error: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by luisfuertes** [comment] 2017-01-18 17:20
@adrianotadao thanks for answer.

I tried to add `libRNGoogleSignin.a` to Share target `Link Binary With Libraries` List  
but `libRNGoogleSignin.a` cant compile with `ObjC`  on `Other Linker Flags`, but without this, Extension cant works

**Comment by adrianotadao** [comment] 2017-01-18 19:41
@luisfuertes I need to confess. React-native is almost a magic box. =l I don't know how can I help you. I'm having problems here and it's very painful

**Comment by alinz** [comment] 2017-01-20 13:01
@luisfuertes can you provide a sample project/repo so I can jump on it. I might have more clear visions and solutions once I see the problems on my computer.

**Comment by ollar** [comment] 2017-02-06 12:50
Hey guys. Any updates in this issue?

**Comment by alinz** [comment] 2017-02-06 14:40
@ollar I can go on and investigate on this issue unless some one creates a sample project. I am using this project into couple of apps and so far no problem.

**Comment by johuder33** [comment] 2017-02-06 17:10
Hi, guys, I am using react-native-share-extension, everything goes good, but I am facing a little problem, I am trying to use Alert API from react-native package, but it doesn't work, anyone has worked with that before ?

here my code : 

```javascript
/**
 * Created by juordergonzalezquinonez on 06-02-17.
 */
import React, { Component } from 'react'
import ShareExtension from 'react-native-share-extension'

import {
  Text,
  TextInput,
  View,
  TouchableOpacity
} from 'react-native'

export default class Share extends Component {
  constructor(props, context) {
    super(props, context)
    this.state = {
      isOpen: true,
      type: '',
      value: '',
      raw: ''
    }
  }

  async componentDidMount() {
    try {
      const data = await ShareExtension.data();
      const { type, value } = data;
      this.setState({
        type,
        value,
        raw: JSON.stringify(data)
      })
    } catch(e) {
      console.log('errrr', e)
    }
  }

  onClose() {
    Alert.alert('title', "My message to alert!!!");
    //ShareExtension.close();
  }

  closing = () => {
    this.setState({
      isOpen: false
    })
  };

  render() {
    return (
      <View style={{ flex: 1, borderColor: 'black', backgroundColor:"pink", opacity: 0.5, borderWidth: 1}}>
        <TouchableOpacity onPress={this.onClose}>
          <Text>Close</Text>
          <Text>type: { this.state.type }</Text>
          <Text>value: { this.state.value }</Text>
          <View style={{marginVertical: 20}}/>
          <Text>RAW: { this.state.raw }</Text>
        </TouchableOpacity>
      </View>
    )
  }
}

```

**Comment by alinz** [comment] 2017-02-06 21:35
@johuder33 unfortunately that not possible. the reason is that, I'm instantiating share extension with  Just the controller and there is no application window. Alert requires an application window. I think it is possible but at the moment I am busy with stuff but I would accept PR for anyone who wants to implement it. 

Your alternative way is using `react-native-modalbox` to show the alert box and you can style it the way you want it. I have prototype a quick example.

```js
import React, { Component } from 'react'
import { StyleSheet, View, Text, Alert } from 'react-native'
import Modal from 'react-native-modalbox'
import ShareExtension from 'react-native-share-extension'

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  },
  alert: {
    width: 200,
    height: 100,
    backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center'
  }
})

export default class Share extends Component {
  constructor(props, context) {
    super(props, context)

    this.state = {
      showAlert: false,
      message: ''
    }
  }
  onClose() {
    ShareExtension.close()
  }

  showAlert(message) {
    this.setState({
      showAlert: true,
      message: message
    })
  }

  async componentDidMount() {
    const result = await ShareExtension.data()
    setTimeout(() => {
      this.showAlert(result.value)
    }, 3000)
  }

  render() {
    return (
      <Modal backdrop={false}
            style={{ backgroundColor: 'green' }} 
            position="center" 
            isOpen={true} 
            onClosed={this.onClose}>
        <View style={styles.container}>
          <Text>This is Share Extension2</Text>
        </View>
        <Modal backdrop={false}
              style={styles.alert} 
              position="center" 
              isOpen={this.state.showAlert}>
          <View style={styles.container}>
            <Text>{this.state.message}</Text>
          </View>     
        </Modal>
      </Modal>
    )
  }
}
```

hmmm, about your second part of your question,  I don't quite get it. can you elaborate on that? if you don't import them then you can use them unless you wrap them with another component inside another file and import the custom component into this file.

**Comment by johuder33** [comment] 2017-02-07 13:37
@alinz I understand, I would like to help you with a PR, but I am not a Objetive-C developer, I am learning right now, because I would like to build some module for RN, now concerning about my second question, please forget about it, I don't know what I was thinking about at that moment hahaha!.

But there is a thing that I can't get it.

how can you debug your share extension ? I tried enabling remote debugging but not luck, do you know any way to debug into the share extension app ?

Thanks

**Comment by alinz** [comment] 2017-02-07 14:55
what you have to do is from top left corner of xcode,
![screen shot 2017-02-07 at 9 50 26 am](https://cloud.githubusercontent.com/assets/967050/22696127/ff7ed552-ed1a-11e6-96c3-41b8bf728fe0.png)

select the share extension

![screen shot 2017-02-07 at 9 50 40 am](https://cloud.githubusercontent.com/assets/967050/22696131/02114dd6-ed1b-11e6-9d52-cd75b2aedcc9.png)

and run it. once you do that you will be prompt to run it in safari.

then you would be able to debug it.

One thing though, you have to run your share extension in safari manually, it doesn't run automatically. once you do that then xcode will log and display everything for you.

cheers

**Comment by johuder33** [comment] 2017-02-10 20:21
@alinz great, now it`s working, thanks too much.

**Comment by juhaelee** [comment] 2017-03-23 15:00
Hey @alinz! You said:

> At the moment, I'm doing exactly like that in my app. If users are not logged in, I push them back to main app for login procedure.

Are you doing this by using React-native's Linking library? I'm trying to achieve this by doing something like this in the share extension if the user is not logged in:
```
const url = "myapp://"
Linking.canOpenURL(url).then(supported => {
            if (!supported) {
              console.log('can not open url')
            } else {
              Linking.openURL(url);
            }
          })
```

Is this what you did? Doing this doesn't seem to be doing anything for me. I tried typing myapp:// in safari and it does execute the applink correctly

**Comment by alinz** [comment] 2017-03-24 04:18
@juhaelee you just have to remember that in order for Linking to work user interaction must be performed. What I mean by this is user must initiate the trigger by tapping on request. When you type the url in safari and hit go, you as a user trigger the start.

what you have to do is show a message or open the dialogue to ask the user to launch the app, once the user accept then the process will work.

In other hand, you can't programatically open the any app without user approval.

**Comment by simsim0709** [comment] 2017-03-30 10:01
@alinz 
How can I share login token in ios?
I first tried this package in android. It's working very well, but no luck in ios.
I store login token in `AsyncStorage`, and if there is login token I send request to rest api server.
Android is very fine, but I can't get the token data from share extension in ios.
It's always `null`,  although, in android it's working very well. 

According to you, 
> they should login in your app first and then you can access the the token from share extension. 

Do I have to try something else?

Sorry, for beginner's question.. I do not have ios knowledge.

**Comment by luisfuertes** [comment] 2017-03-30 10:16
@simsim0709 AsyncStorage isnt the same API that NSUser​Defaults, you can use this component to share token with NSUserDefaults: https://github.com/alinz/react-native-swiss-knife

**Comment by alinz** [comment] 2017-03-30 13:47
@simsim0709, as @luisfuertes mentioned, I have implemented react-native-swiss-knife to fix this issue of sharing anything between App and Share extensions. let me know how things go.

**Comment by luisfuertes** [comment] 2017-03-31 09:12
@alinz and about this bug, for clarify, if you install some component incompatible with `-ObjC` and `-lc++` you cant use react-native-share-extension because you must add all your main project iOS librarys to the extension app

**Comment by alinz** [comment] 2017-03-31 14:16
@luisfuertes unfortunately even if I remove it, it won't be compatible anymore as of version 41 of react-native. from 41 they will add the `-ObjC` and `lc++` by default to the build schema. here's the PR for that https://github.com/facebook/react-native/commit/e0c3d56d3a5dcc68c1a7585275a051d781ade914

I think it's time for open PR to those library and make them compatible with these flags.

**Comment by njt1982** [comment] 2017-06-22 13:52
@adrianotadao @alinz I have raised https://github.com/devfd/react-native-google-signin/issues/251 as I am having the same issue. 

```
2017-06-22 14:44:25.327 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'RNGoogleSignin.BUTTON_SIZE_ICON')
2017-06-22 14:44:25.328 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'RNGoogleSignin.BUTTON_SIZE_ICON')
```

We cannot include the Google library as it is not compatible with ObjC. Any ideas on how to progress with this problem?

**Comment by alinz** [comment] 2017-06-22 14:12
Unfortunately this is not the react-native-share-extension issue anymore. one quick advise, do not let user login with share extension. Share extension meant to be do one thing and one thing only. The user has to login into your main app and your main app share the credential with share extension. 

I'm going to close this issue. Feel free to continue the discussion.

**Closed by alinz** 2017-06-22 14:12 UTC

**Comment by njt1982** [comment] 2017-06-22 14:55
Agreed about the login - however, I am not doing that here. As with @adrianotadao earlier, the login is from the main app. TBH I am a bit lost as to why the extension is even trying to include this.

**Comment by vishim** [comment] 2017-06-29 10:16
@juhaelee - Did you find a solution for opening the app 

> what you have to do is show a message or open the dialogue to ask the user to launch the app, once the user accept then the process will work.

@alinz Do you have an example of how to do this?

**Comment by xuechinahb** [comment] 2017-07-10 03:17
Same......
Now, I have a simple project  with basic configuration. [https://github.com/xuechinahb/ShareApp](url). react native V0.39.2. Only run on iphone. I open safari, then click share icon, nothing happened.

**Comment by alinz** [comment] 2017-07-10 03:19
@xuechinahb the link that you provided is broken. is this a private repo?

**Comment by xuechinahb** [comment] 2017-07-10 04:01
@alinz  try agin .

**Comment by xuechinahb** [comment] 2017-07-10 08:09
It is much  strange. Sometimes it is ok,  can show modal. Sometimes Safari has no response, Safari is dead, I must kill Safari and restart it. Moreover, as mentioned above, nothing happened. 
When two projects or above  install react-native-share-extension, build and run with the one iphone, Safari will be no response.
When init a blank project, share extension works. But integrated into my current react-native app project, it does not work, Safari has no response.

**Comment by ncnlinh** [comment] 2017-08-17 18:25
I found a way to hack through this. In fact, you can even skip some of the libraries in **this** 


![image](https://user-images.githubusercontent.com/7568367/29426993-f6ee1ace-83ba-11e7-89b2-f21aeb52015f.png) linking library part of the installation and just import whatever you need for the ShareExtension to run (such as basic libraries like `libReact.a`, `libRCTImage.a`, `libRCTLinking.a`, `libRCTNetwork.a`, `libRCTText.a`, etc...) and therefore not importing `libRNGoogleSignin.a` and other culprits.

In the `.m` file (i.e.`MyShareEx.m`), instead of using `@"index.ios"` for jsBundleURLForBundleRoot, change to something like `@"share.ios"`.

In your `index.ios.js` file, don't do `AppRegistry.registerComponent()` for the `MyShareEx` module but create a new file at your root called `share.ios.js` and put `AppRegistry.registerComponent()` there.

The reason for this is that, `MyShareEx.m` will load the whole `index.ios.js` file just for the share extension (and that's not necessary); therefore register whatever screens/functionalities on your main app, including the Google Sign In button (and that's why you will have to link the `libRNGoogleSignin.a` so that the Javascript side won't scream out _omg_, `undefined is not an object (evaluating 'RNGoogleSignin.BUTTON_SIZE_ICON')`

One thing that I still haven't figured out is if when the app is bundled and exported, how will RN bundle both of the js files that are needed for the main app and the share extension. I will need to try exporting the app and try it out. Anyone with more knowledge on this can enlighten me?

Hope that this will help.

**Comment by alinz** [comment] 2017-08-17 19:43
@ncnlinh that is really good and as you mentioned in the last section, unless you want to hack the bundler itself. And that is why I put the whole registration there. one way to solve this elegantly without doing too much hack is [this](https://github.com/alinz/react-native-share-extension/issues/48#issuecomment-317587122). 

you simply use `require` instead of `import` only at the boot time so you won't load unnecessary code. 

> as a side note: in my experience with react-native, try not to modify the internals as the next version might break your changes.

**Comment by pkantsedalov** [comment] 2018-02-08 09:09
@alinz 
First of all thank you for your work.

About this issue: I can't get rid of it simply using `require` instead of `import`. 
BTW to make it work locally @ncnlinh's solution using separate `share.js` file works fine.

But am I right that in order to bundle an app I have to keep one - `index.js` - file, not two of them?

**Comment by Derpidy** [comment] 2018-06-14 22:18
@ncnlinh I did exactly the same thing, and it work great on Simulator, but doesn't load at all on real device. It there any fix out there or is this dead ?

**Comment by sujitkaulavkar123** [comment] 2019-05-08 08:25
Hi @alinz , I am using the react-native-share-extension in one of my project. I have integrated the package as suggested. I am able to see the UI when I am sharing the text in Android. But in iOS, I can't see the UI.
     After doing some research, I found that whenever I am importing another file, it stops working. This is specifically in **iOS** only. Following is my code. 

```
RCT_EXPORT_MODULE();
- (UIView*) shareView {
  NSURL *jsCodeLocation;
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"shareIndex" fallbackResource:nil];
//
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"EWA_Chat"
                                               initialProperties:nil
                                                   launchOptions:nil];
  rootView.backgroundColor = nil;
  // Uncomment for console output in Xcode console for release mode on device:
  // RCTSetLogThreshold(RCTLogLevelInfo - 1);
  
  return rootView;
}
@end
```

```
   import { View, AppRegistry } from 'react-native';
import React, { Component } from 'react';
import Share from './Share';   // **This line is creating issue**
export default class shareIndex extends Component {
	render() {
		return (
			<View style={{ flex: 1, backgroundColor: 'blue' }}>
                             <Share/>	// **This line is creating issue**			
			</View>
		)
	}
}
AppRegistry.registerComponent("EWA_Chat", () => shareIndex);
``` 

   Now, whenever I am importing the `Share` file, it is not loading the view. If I comment out the Share import and <Share/> then I can see the blue view. 

  I want to load other from share extension. Can you guide me how can I achieve it or point out what I am missing here. 
  Thanks

**Comment by pisacode** [comment] 2019-07-28 21:19
Creating a new index file for share component fixed it for me
